const Colors = {
  white: '#ffffff',
  black: '#000000',
  nice_blue: '#1982B4',
  half_baked: '#82BEDB',
  powder_blue: '#BDDDED',
  moonstone_blue: '#68AFD3',
  mediumState_blue: '#4315FF',
  lavender: '#CBCEF9',
  lavender_light: '#EFEDFF',
  lavender_deep: '#B1A8FF',
  navy_blue: '#1F00FF',
  navy_blue_deep: '#160E52',
};

const Icons = {
  logo: require('../assets/icon/photoshop.png'),
  plus: require('../assets/icon/plus.png'),
  user: require('../assets/icon/user.png'),
  menu: require('../assets/icon/menu.png'),
  home: require('../assets/icon/home.png'),
  create: require('../assets/icon/create.png'),
  imgBackGround: require('../assets/images/imgBackground.png'),
  hide: require('../assets/icon/hide.png'),
  show: require('../assets/icon/show.png'),
  edit: require('../assets/icon/edit-profile.png'),
  myOrders: require('../assets/icon/shopping-bag.png'),
  address: require('../assets/icon/location.png'),
  payment: require('../assets/icon/wallet.png'),
  logout: require('../assets/icon/logout.png'),
  sidebar: require('../assets/icon/sidebar.png'),
  back: require('../assets/icon/arrow-left.png'),
  bin: require('../assets/icon/trash.png'),
  visa: require('../assets/icon/Vector.png'),
  Success: require('../assets/icon/Success.png'),
  delete: require('../assets/icon/delete.png'),
  facebook: require('../assets/icon/facebook.png'),
  instagram: require('../assets/icon/instagram.png'),
  linkedin: require('../assets/icon/linkedin.png'),
  visa: require('../assets/images/visa.png'),
  master: require('../assets/images/master.png'),
  discover: require('../assets/images/discover.png'),
  express: require('../assets/images/express.png'),
  FooterBack: require('../assets/images/FooterBack.png'),
  aboutBack: require('../assets/images/aboutBack.png'),
  aboutEffect: require('../assets/images/aboutEffect.png'),
  aboutPic: require('../assets/images/aboutPic.png'),
  aboutPic2: require('../assets/images/aboutPic2.png'),
  aboutPic3: require('../assets/images/aboutPic3.png'),
  about: require('../assets/icon/info.png'),
  add: require('../assets/icon/add.png'),
  contactBack2: require('../assets/images/contactBack2.png'),
  addImage: require('../assets/images/addImage.png'),
  productBack: require('../assets/images/productBack.png'),
  vape: require('../assets/images/vape.png'),
  cart: require('../assets/icon/cart.png'),
  search: require('../assets/icon/search.png'),
  filter: require('../assets/icon/filter.png'),
  homeback: require('../assets/images/homeback.png'),
  saleProduct: require('../assets/images/saleProduct.png'),
  sell: require('../assets/icon/tag.png'),
  Shipping: require('../assets/icon/Shipping.png'),
  close: require('../assets/icon/close.png'),
  sampleProfilePic: require('../assets/images/reviewer.jpeg'),
  logo1: require('../assets/icon/logo1.png'),
  billingback: require('../assets/images/billingback.png'),
  paysymbol: require('../assets/icon/down.png'),
  icici: require('../assets/icon/icici.png'),
  exit: require('../assets/icon/exit.png'),
  passwordChange2: require('../assets/icon/passwordChange2.json'),
  ordersuccess: require('../assets/icon/ordersuccess.json'),
  brandLogo: require('../assets/icon/brandLogo.png'),
  loadingsplash: require('../assets/icon/loadingsplash.json'),
};

const Brands = [
  {
    title: 'Al Fakeher Crown 8000',
    Logo: require('../assets/images/products/Ellipse12.png'),
  },
  {
    title: 'Flum Collection Box',
    Logo: require('../assets/images/products/Ellipse14.png'),
  },
  {
    title: 'Flum Mello 20K',
    Logo: require('../assets/images/products/Ellipse16.png'),
  },
  {
    title: 'Funky Republic Ti7000',
    Logo: require('../assets/images/products/Ellipse18.png'),
  },
  {
    title: 'Hyppe Max Air 5000',
    Logo: require('../assets/images/products/Ellipse20.png'),
  },
  {
    title: 'Lost Mary OS5000',
    Logo: require('../assets/images/products/Ellipse13.png'),
  },
  {
    title: 'My Shisha XL',
    Logo: require('../assets/images/products/Ellipse15.png'),
  },
  {
    title: 'Spaceman Prism 20K',
    Logo: require('../assets/images/products/Ellipse17.png'),
  },
];

export const Fonts = {
  Mochiy_Regular: 'MochiyPopPOne-Regular',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Rubik_Regular: 'RubikGlitchPop-Regular',
};

export {Colors, Icons, Brands};
